# This pipeline will:
#    1. Create a local branch from main
#    2. Add an upstream remote for https://github.com/NetchexGlobalDev/ResourceModules.git
#    3. Merge the upstream/main into the new local branch
#    4. Determine if there are any changes in the new local branch
#        1. If there are changes, create a pull request from the new local branch to main

name: ".Platform - Sync from Public Upstream"

pr: none

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday Update
    branches:
      include:
        - main

variables:
  - template: "../../settings.yml"
  - name: pipelinePrincipalGitUserName
    value: "NetchexGlobalDev"
  - name: pipelinePrincipalGitUserEmail
    value: "devops@netchexonline.com"
  - name: upstreamRepository
    value: "https://github.com/NetchexGlobalDev/ResourceModules.git"
  - name: organizationName
    value: "netchexonline"

jobs:
  - job: Sync_From_Upstream
    pool:
      ${{ if ne(variables.vmImage, '') }}:
        vmImage: ${{ variables.vmImage }}
      ${{ if ne(variables.poolName, '') }}:
        name: ${{ variables.poolName }}
    steps:
      - checkout: self
        persistCredentials: true

      - task: PowerShell@2
        displayName: "Merge changes from upstream"
        inputs:
          targetType: inline
          pwsh: true
          verbosePreference: continue
          script: |
            'Configure git to use the pipeline principal' | Write-Verbose;
            git config --global user.name '$(pipelinePrincipalGitUserName)';
            git config --global user.email '$(pipelinePrincipalGitUserEmail)';

            'Fetch all on origin' | Write-Host -Foreground 'Yellow';
            git fetch --all;

            'Checkout main' | Write-Verbose;
            git checkout main;

            'Create a new branch from main' | Write-Verbose;
            $Timestamp = Get-Date -Format 'yyyyMMdd.HHmmss';
            $NewBranchName = "upstream-sync/$Timestamp";
            git checkout -b $NewBranchName main;

            'Add the upstream remote' | Write-Verbose;
            git remote add -f -t main -m main upstream $(upstreamRepository);

            'Merge the upstream/main into the new branch' | Write-Verbose;
            git merge upstream/main --allow-unrelated-histories --no-ff;

            'Add all changes to the new branch' | Write-Verbose;
            git add .;

            'Commit to the new branch' | Write-Verbose;
            git commit -m "Upstream Merge: $Timestamp";

            'Determine if there are any changes in the new branch' | Write-Verbose;
            git status;

            'Publish new branch' | Write-Verbose;
            git push origin;

            Install-Module -Name 'VSTeam' -Force -Verbose:$false;
            Import-Module -Name 'VSTeam' -Verbose:$false;

            'Connect to Azure DevOps' | Write-Verbose;
            Set-VSTeamAccount -Account '$(organizationName)' -Token '$(System.AccessToken)' -UseBearerToken -Verbose:$false;

            'Get Repository' | Write-Verbose;
            $Repository = Get-VSTeamGitRepository -ProjectName '$(System.TeamProject)' -Name '$(Build.Repository.Name)' -Verbose:$false;

            $Repository;

            'Create Pull Request' | Write-Verbose;
            Add-VSTeamPullRequest -Verbose:$false `
              -ProjectName '$(System.TeamProject)' `
              -RepositoryId $(Build.Repository.ID) `
              -SourceRefName "refs/heads/$NewBranchName" `
              -TargetRefName 'refs/heads/main' `
              -Title "Upstream Merge: $Timestamp" `
              -Description "Upstream Merge: $Timestamp"
              # ` -Draft
